[package]
name = "zabawa-notification-view"
version = "0.1.1"
edition.workspace = true

[dependencies]
hypertext = { workspace = true }
zabawa-notification-domain = { workspace = true }
zabawa-view-common = { workspace = true }
