[package]
name = "zabawa-name"
version = "0.1.1"
edition.workspace = true

[dependencies]
derive_more = { workspace = true }
deunicode = { workspace = true }
thiserror = { workspace = true }
zabawa-validation = { workspace = true }
